import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Geeze Market",
  description: "Generated by Andargachew",

  icons: {
    icon: "/asset/Asset 3.svg",
  },

  openGraph: {
    title: "Geeze Market",
    description: "Generated by Andargachew",
    images: [
      {
        url: "/asset/Asset 3.svg",
        width: 1200,
        height: 630,
        alt: "Geeze Market Logo",
      },
    ],
  },

  twitter: {
    card: "summary_large_image",
    title: "Geeze Market",
    description: "Generated by Andargachew",
    images: ["/asset/Asset 3.svg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
